require("indent_guides").setup({
	indent_levels = 15,
	indent_guide_size = 1,
	indent_start_level = 3,
	indent_enable = true,
	indent_pretty_mode = true,
	indent_space_guides = true,
	indent_tab_guides = true,
	indent_soft_pattern = "\\s",
	exclude_filetypes = {
		"which_key",
		"help",
		"dashboard",
		"dashpreview",
		"NvimTree",
		"vista",
		"sagahover",
		"sagasignature",
		"packer",
		"log",
		"lspsagafinder",
		"lspinfo",
    "dapui_breakpoints",
    "dapui_watches",
    "dapui_stacks",
    "dapui_scopes",
    "dap-repl",
	},
	even_colors = { fg = '#565f89',bg = '#24283b' };
	odd_colors = { fg = '#565f89',bg = '#24283b' };
})
